### ISSUE TITLE
PRACTICA 9 - EQUIPO WAR

### ISSUE THREAD

**Issue by ArcangelGC** [SistemasTecTlaxiaco/actividad-9-diagrama-de-clases-secuencia-equipowar#1]
[PRACTICA 9 F - EQUIPO WAR.pdf](https://github.com/user-attachments/files/18071121/PRACTICA.9.F.-.EQUIPO.WAR.pdf)

**Comment by HECTOR-KDM02** [comment]
30 puntos 


Todo lo revisado va deacuerdo con la rubrica sin embargo se podria mejorar un poco mas para mejor presentación del proyecto

**Comment by HECTOR-KDM02** [comment]
30 puntos 


Todo se entrego en forma sin detalles nadamas mejorar la presentacion del documento poniendo los espacios donde es debido para separar los apartados y una mejor presentacion

**Comment by josealfredo79** [comment]
Faltan los parametros en las clases por favor..favor de checar...

**Comment by ArcangelGC** [comment]
CORREGIDO

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
